[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
interest = "FqzkXZdwYjurnUKetJCAvaUw5WAqbwzU6gZEwydeEfqS"

[programs.devnet]
interest="J4bfWKCuz2J1gzbwhosrhRV5Q1bQATjvAmnzP7SMYptY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
